import sqlite3

def check_db(label, path):
    db = sqlite3.connect(path)
    c = db.cursor()
    print(f"=== {label} ===")
    c.execute("SELECT COUNT(*) FROM smartwork_tips")
    print(f"  SmartWork tips: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM notifications")
    print(f"  Notifications: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM risk_scores")
    print(f"  Risk scores: {c.fetchone()[0]}")
    c.execute("SELECT status FROM claims WHERE id = 62")
    r = c.fetchone()
    print(f"  Claim 62 status: {r[0] if r else 'NOT FOUND'}")
    c.execute("SELECT COUNT(*) FROM claims c LEFT JOIN imd_trigger_events ie ON ie.id = c.trigger_event_id WHERE ie.id IS NULL")
    print(f"  Orphan claims: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM imd_trigger_events")
    print(f"  IMD triggers: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM users")
    print(f"  Users: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM worker_profiles")
    print(f"  Profiles: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM policies")
    print(f"  Policies: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM payouts")
    print(f"  Payouts: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM transactions")
    print(f"  Transactions: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM daily_income_logs")
    print(f"  Income logs: {c.fetchone()[0]}")
    c.execute("SELECT COUNT(*) FROM fraud_signals")
    print(f"  Fraud signals: {c.fetchone()[0]}")
    db.close()

check_db("MAIN DB (552KB)", r'C:\Users\aksha_mfctx7k\OneDrive\Desktop\InsureOn_S\InsureOn\InsureOn\insureon.db')
check_db("BACKEND DB (200KB)", r'C:\Users\aksha_mfctx7k\OneDrive\Desktop\InsureOn_S\InsureOn\InsureOn\backend\insureon.db')
